### ISSUE TITLE
Fix `GetRepoPath` so it correctly returns the path that Git uses

### ISSUE THREAD

**Issue by Southclaws** [Southclaws/gitwatch#2]
This works for ssh but not for http git repos.

It results in https repos getting a name like `https` instead of the actual project name.

It would also be much better to just use a structure for repos so the user can specify a custom path for each repo. Especially useful for IaaC setups where the deployment configuration repo for a project has a generic name like `deployment`.

**Comment by ADRFranklin** [comment]
This is weird, because the tests seem to return the correct path and name for it. This is really strange behavior lol.
